https://gymnasium.farama.org/  
pekiştirmeli öğrenme için örnek çalışmalar

In [1]:
!pip install numpy==1.23.5

In [5]:
import gym
import random
import numpy as np


In [6]:
environment = gym.make("FrozenLake-v1", is_slippery=False, render_mode="ansi", new_step_api=True)
environment.reset()

nb_states = environment.observation_space.n
nb_actions = environment.action_space.n
qtable = np.zeros((nb_states, nb_actions))

print("Q-table:")
print(qtable)

action = environment.action_space.sample()

"""
sol: 0
asagi: 1
sag: 2
yukari: 3
"""

new_state, reward, terminated, truncated, info = environment.step(action)
done = terminated or truncated

Q-table:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
